services:
  cosmo-api:
    # image: cosmo-bot-be
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmo-api
    env_file:
      - .env.deployment.local
    ports:
      - "8083:8083"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock